### PR TITLE
Fix hook template for apps with different package names, add hook_template config option

### LINKED ISSUE #363: gravitybee does not handle packages with differently named modules well
**Describe the bug**
Example:
https://github.com/miurahr/aqtinstall

the aqtinstall package has its only module named "aqt".

when running gravitybee without args in the dir, it will fail:

```
(venv) λ gravitybee.exe 
GravityBee CLI, 0.1.86
running bdist_wheel
running build
running build_py
creating build
creating build\lib
creating build\lib\aqt
copying aqt\archives.py -> build\lib\aqt
copying aqt\exceptions.py -> build\lib\aqt
copying aqt\helper.py -> build\lib\aqt
copying aqt\installer.py -> build\lib\aqt
copying aqt\metadata.py -> build\lib\aqt
copying aqt\updater.py -> build\lib\aqt
copying aqt\version.py -> build\lib\aqt
copying aqt\__init__.py -> build\lib\aqt
copying aqt\__main__.py -> build\lib\aqt
copying aqt\combinations.json -> build\lib\aqt
copying aqt\logging.ini -> build\lib\aqt
copying aqt\settings.ini -> build\lib\aqt
installing to .\.pyppyn\temp
running install
running install_lib
creating .pyppyn\temp
creating .pyppyn\temp\aqt
copying build\lib\aqt\archives.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\combinations.json -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\exceptions.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\helper.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\installer.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\logging.ini -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\metadata.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\settings.ini -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\updater.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\version.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\__init__.py -> .\.pyppyn\temp\.\aqt
copying build\lib\aqt\__main__.py -> .\.pyppyn\temp\.\aqt
running install_egg_info
running egg_info
writing aqtinstall.egg-info\PKG-INFO
writing dependency_links to aqtinstall.egg-info\dependency_links.txt
writing entry points to aqtinstall.egg-info\entry_points.txt
writing requirements to aqtinstall.egg-info\requires.txt
writing top-level names to aqtinstall.egg-info\top_level.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt'
warning: no files found matching '*.yml' under directory 'aqt'
warning: no files found matching '*.dia' under directory 'docs'
warning: no files found matching '*.yml' under directory 'docs'
warning: no files found matching '*.svg' under directory 'docs'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
warning: no previously-included files found matching 'qtaccount.ini'
warning: no previously-included files found matching 'aqtinstall.log'
adding license file 'LICENSE'
writing manifest file 'aqtinstall.egg-info\SOURCES.txt'
Copying aqtinstall.egg-info to .\.pyppyn\temp\.\aqtinstall-2.0.0b4.dev48-py3.9.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating .\.pyppyn\temp\aqtinstall-2.0.0b4.dev48.dist-info\WHEEL
creating '.\.pyppyn\dist\aqtinstall-2.0.0b4.dev48-py2.py3-none-any.whl' and adding '.\.pyppyn\temp' to it
adding 'aqt/__init__.py'
adding 'aqt/__main__.py'
adding 'aqt/archives.py'
adding 'aqt/combinations.json'
adding 'aqt/exceptions.py'
adding 'aqt/helper.py'
adding 'aqt/installer.py'
adding 'aqt/logging.ini'
adding 'aqt/metadata.py'
adding 'aqt/settings.ini'
adding 'aqt/updater.py'
adding 'aqt/version.py'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/LICENSE'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/METADATA'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/WHEEL'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/entry_points.txt'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/top_level.txt'
adding 'aqtinstall-2.0.0b4.dev48.dist-info/RECORD'
removing .\.pyppyn\temp
2021-07-21 18:37:11,486 - gravitybee - INFO - Arguments:
2021-07-21 18:37:11,486 - gravitybee - INFO - app_name: aqtinstall
2021-07-21 18:37:11,486 - gravitybee - INFO - app_version: 2.0.0b4.dev48
2021-07-21 18:37:11,487 - gravitybee - INFO - operating_system: windows
2021-07-21 18:37:11,487 - gravitybee - INFO - machine_type: amd64
2021-07-21 18:37:11,487 - gravitybee - INFO - console_script: aqt
2021-07-21 18:37:11,487 - gravitybee - INFO - pkg_name: aqt
2021-07-21 18:37:11,487 - gravitybee - INFO - script_path: C:\workspace\testpyshit\aqtinstall\venv\Scripts\aqt-script.py
2021-07-21 18:37:11,488 - gravitybee - INFO - pkg_dir: .
2021-07-21 18:37:11,488 - gravitybee - INFO - src_dir: .
2021-07-21 18:37:11,488 - gravitybee - INFO - name_format: {an}-{v}-standalone-{os}-{m}
2021-07-21 18:37:11,489 - gravitybee - INFO - clean: False
2021-07-21 18:37:11,489 - gravitybee - INFO - work_dir: .gravitybee\build\54ae3588ea8d11eb
2021-07-21 18:37:11,489 - gravitybee - INFO - onedir: False
2021-07-21 18:37:11,489 - gravitybee - INFO - staging_dir: .gravitybee\dist
2021-07-21 18:37:11,490 - gravitybee - INFO - with_latest: False
2021-07-21 18:37:11,490 - gravitybee - INFO - sha: info
2021-07-21 18:37:11,491 - gravitybee - INFO - Package generator:
2021-07-21 18:37:11,491 - gravitybee - INFO - standalone_name: aqtinstall-2.0.0b4.dev48-standalone-windows-amd64
2021-07-21 18:37:11,511 - gravitybee - INFO - Created hook file: .gravitybee\build\54ae3588ea8d11eb\hooks\hook-aqt.py
2021-07-21 18:37:11,513 - gravitybee - INFO - PyInstaller commands:
2021-07-21 18:37:11,513 - gravitybee - INFO - pyinstaller, --noconfirm, --onefile, --name, aqtinstall-2.0.0b4.dev48-standalone-windows-amd64, --paths, ., --additional-hooks-dir, .gravitybee\build\54ae3588ea8d11eb\hooks, --specpath, .gravitybee\build\54ae3588ea8d11eb, --workpath, .gravitybee\build\54ae3588ea8d11eb\build, --distpath, .gravitybee\build\54ae3588ea8d11eb\dist, --hidden-import, aqt, --hidden-import, 
pkg_resources.py2_warn, .gravitybee\build\54ae3588ea8d11eb\55c0ced7ea8d11eb_aqt.py
2021-07-21 18:37:20,358 - gravitybee - ERROR - 71 INFO: PyInstaller: 4.4
71 INFO: Python: 3.9.6
78 INFO: Platform: Windows-10-10.0.19041-SP0
84 INFO: wrote .gravitybee\build\54ae3588ea8d11eb\aqtinstall-2.0.0b4.dev48-standalone-windows-amd64.spec
89 INFO: UPX is not available.
98 INFO: Extending PYTHONPATH with paths
['C:\\workspace\\testpyshit\\aqtinstall\\.gravitybee\\build\\54ae3588ea8d11eb',
 'C:\\workspace\\testpyshit\\aqtinstall',
 'C:\\workspace\\testpyshit\\aqtinstall\\.gravitybee\\build\\54ae3588ea8d11eb']
109 INFO: checking Analysis
110 INFO: Building Analysis because Analysis-00.toc is non existent
110 INFO: Initializing module dependency graph...
113 INFO: Caching module graph hooks...
137 INFO: Analyzing base_library.zip ...
2076 INFO: Processing pre-find module path hook distutils from 'c:\\workspace\\testpyshit\\aqtinstall\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2077 INFO: distutils: retargeting to non-venv dir 'c:\\python39\\lib'
4461 INFO: Caching module dependency graph...
4622 INFO: running Analysis Analysis-00.toc
4635 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python39\python.exe
4690 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\python39\python39.dll
4824 INFO: Analyzing .gravitybee\build\54ae3588ea8d11eb\55c0ced7ea8d11eb_aqt.py
4956 INFO: Processing pre-find module path hook site from 'c:\\workspace\\testpyshit\\aqtinstall\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
4956 INFO: site: retargeting to fake-dir 'c:\\workspace\\testpyshit\\aqtinstall\\venv\\lib\\site-packages\\PyInstaller\\fake-modules'     
6541 INFO: Analyzing hidden import 'aqt'
6797 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\workspace\\testpyshit\\aqtinstall\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
8338 INFO: Analyzing hidden import 'pkg_resources.py2_warn'
8339 ERROR: Hidden import 'pkg_resources.py2_warn' not found
8339 INFO: Processing module hooks...
8339 INFO: Loading module hook 'hook-aqt.py' from 'C:\\workspace\\testpyshit\\aqtinstall\\.gravitybee\\build\\54ae3588ea8d11eb\\hooks'... 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'aqtinstall'
Traceback (most recent call last):
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 381, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\workspace\testpyshit\aqtinstall\.gravitybee\build\54ae3588ea8d11eb\hooks\hook-aqt.py", line 10, in <module>
    datas += collect_data_files('aqtinstall')
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 774, in collect_data_files   
    pkg_base, pkg_dir = get_package_paths(package)
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 545, in get_package_paths    
    file_attr = get_module_file_attribute(package)
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 399, in get_module_file_attribute
    raise ImportError('Unable to load module attribute') from e
ImportError: Unable to load module attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\workspace\testpyshit\aqtinstall\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\building\build_main.py", line 758, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\building\build_main.py", line 705, in build
    exec(code, spec_namespace)
  File ".gravitybee\build\54ae3588ea8d11eb\aqtinstall-2.0.0b4.dev48-standalone-windows-amd64.spec", line 7, in <module>
    a = Analysis(['55c0ced7ea8d11eb_aqt.py'],
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\building\build_main.py", line 254, in __init__
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 373, in process_post_graph_hooks                                                                ", line 159, in __postinit__
    module_hook.post_graph(analysis)
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\depend\imphook.py", li", line 433, in assemblene 451, in post_graph
    self._load_hook_module()                                                                        ine 373, in process_post_graph_hooks  
  File "c:\workspace\testpyshit\aqtinstall\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 412, in _load_hook_module                                                                        ne 451, in post_graph
    raise ImportErrorWhenRunningHook(
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_aqtne 412, in _load_hook_module required by hook for module C:\workspace\testpyshit\aqtinstall\.gravitybee\build\54ae3588ea8d11eb\hooks\hook-aqt.py. Please check whether module __PyInstaller_hooks_0_aqt actually exists and whether  required by hook for module C:\worksp
the hook is compatible with your version of C:\workspace\testpyshit\aqtinstall\.gravitybee\build\54a module __PyInstaller_hooks_0_aqt actue3588ea8d11eb\hooks\hook-aqt.py: You might want to read more about hooks in the manual and provide all\.gravitybee\build\54ae3588ea8d11eb\ pull-request to improve PyInstaller.                                                               to improve PyInstaller.

2021-07-21 18:37:20,370 - gravitybee - ERROR - PyInstaller exited with error code 1
```

When running gravitybee with `gravitybee.exe --app-name aqt --pkg-name aqtinstall --pkg-dir . --src-dir aqt`, it builds fine, but running the application results in an error:
```
(venv) λ .gravitybee\dist\2.0.0b4.dev48\aqt-2.0.0b4.dev48-standalone-windows-amd64.exe 
Traceback (most recent call last):
  File "24c4a941ea8e11eb_aqt.py", line 33, in <module>
  File "24c4a941ea8e11eb_aqt.py", line 22, in importlib_load_entry_point
  File "importlib\metadata.py", line 524, in distribution
  File "importlib\metadata.py", line 187, in from_name
importlib.metadata.PackageNotFoundError: aqtinstall
[20180] Failed to execute script '24c4a941ea8e11eb_aqt' due to unhandled exception!
```

If I change the name of the package to just `aqt` and reinstall it, then it works fine. This is not really feasible for development and distribution, however.

**Your configuration**
Windows 10
Python 3.9.6
gravitybee master

### PR DESCRIPTION
**Pull request by nikitalita**
Fixes #363

Changes proposed in this pull request:

* Changes hook_template to collect_submodules and collect_data_files from `pkg_name`, instead of `app_name`. This fixes issues with apps with different package names
* adds `--hook-template` option for users to specify their own hook.

Output from Pytest:

```
(venv) λ pytest
=========================================== test session starts ============================================
platform win32 -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\workspace\pypackaging\gravitybee, configfile: setup.cfg
collected 20 items

tests\test_gravitybee.py ....................                                                         [100%]

============================================= warnings summary ============================================= 
venv\lib\site-packages\_pytest\config\__init__.py:1183
  c:\workspace\pypackaging\gravitybee\venv\lib\site-packages\_pytest\config\__init__.py:1183: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================ 20 passed, 1 warning in 213.08s (0:03:33) ================================= 

```

### CODE REVIEW

**Review by lorengordon — COMMENTED** [review]
Change looks pretty solid to me. Will you be able to look at the tests to see if we can add/modify them to get a regression test for this?

**Comment by nikitalita** [comment]
Not quite sure how to do that here; should i create a new test package with a different module name?

**Comment by nikitalita** [comment]
Ok, I added a test for this

**Comment by nikitalita** [comment]
anything else you want me to add to this?

**Review by lorengordon — APPROVED** [review]
Thanks @nikitalita! Looks great, bumped the version and merging now. Will be released in 0.2.0 momentarily...

**Pull request merged**
